INSERT INTO GENEROS (NOMBRE) VALUES('Acción');
INSERT INTO GENEROS (NOMBRE) VALUES('Comedia');
INSERT INTO GENEROS (NOMBRE) VALUES('Drama');
INSERT INTO GENEROS (NOMBRE) VALUES('Fantasia');
INSERT INTO GENEROS (NOMBRE) VALUES('Terror');

INSERT INTO ACTORES (NOMBRE, URL_IMAGEN) VALUES('Hugh Jackman','https://pbs.twimg.com/profile_images/1618060433176383488/z6wO3CHz_400x400.jpg');
INSERT INTO ACTORES (NOMBRE, URL_IMAGEN) VALUES('Keanu Reeves','https://media.revistagq.com/photos/63ef68456c6ab595e1330dca/1:1/w_1080,h_1080,c_limit/Keanu-Reeves.jpg');